### PR TITLE
feat: 🧲 Web SEO

### PR DESCRIPTION
**Pull request by vinnyjth**
## 🐛 Issue

https://differential.slack.com/archives/C03B6DTK5CN/p1698955780655139

Liquid SEO is suffering because of the following issues.
CleanShot 2023-11-03 at 21 41 59@2x

## ✏️ Solution

1. Use React Helmet to pull in appropriate meta tags 🙌 
    - Easy win! Hope you agree :D 
3. Package content item titles into URLs, and encode the original url after the title. 
    - Now when parsing urls, we check to see if it's a vanity url or an apollos id url. If it's a vanity url, we parse it accordingly.  

## 🔬 To Test

Couple things worth testing:

1. Does what I'm claiming work, work? 
  - http://localhost:3000/?id=mens-breakfast-VW5pdmVyc2FsQ29udGVudEl0ZW0tYTA1Mzk4YjQtNzBjZi00MjhjLWI4NWMtYWRhYjEzNDhlZTgx
 2. Do Action List or other embedded feed urls work? 
 4. Do urls of the older style work? 
   - http://localhost:4000/?id=UniversalContentItem-a05398b4-70cf-428c-b85c-adab1348ee81

Long term - I think we ditch the url encoding because it's ugly and makes longs urls. This approach accomplishes our short-term goals without needing shovel work to insert slugs. 

**Disclosure**

@jordanwade I threw this together on a sleepless evening w/out respect for our cycle or planning process. If this is distracting and hinders your or the team's ability to ship cycle goals, I won't be offended if you table, close, or otherwise ignore this work. 

## 📸 Screenshots

CleanShot 2023-11-03 at 21 37 42@2x

### CODE REVIEW

**Comment by jordanwade** [comment]
@vinnyjth looks like we had the same idea, but you took yours further.😁
https://github.com/ApollosProject/apollos-embeds/pull/112

I’ll take a look next week and see we can make this work. Thanks!

**Comment by vinnyjth** [comment]
😂 great minds think alike??You took the Helmet/meta tag portion of this task way farther, whatever route we go we should make sure to pull in your helmet code On Nov 3, 2023, at 10:10 PM, Jordan Wade ***@***.***> wrote:﻿
@vinnyjth looks like we had the same idea, but you took yours further.😁
#112
I’ll take a look next week and see we can make this work. Thanks!

**Comment by calebpanza** [comment]
Are we reviewing this PR or is there another one? Just don't wanna get them mixed up.

@vinnyjth I'm with you on the route you too. Think it makes perfect sense. I'm not overly confident that this is actually gonna affect SEO, though. Lol. In past experience, SEO is really preferential to _path_ based routing. But maybe that's neither here, nor there! It's been a while since I've played in that sandbox (thankfully. Lol)

**Comment by linb1** [comment]
@calebpanza This should be the PR! There was another PR opened by Jordan but I've added that work into this PR

**Comment by jordanwade** [comment]
@linb1 this is looking good, one thing I noticed.

Should this url be the url of the content item instead of the root url?
image

**Comment by linb1** [comment]
@jordanwade Whoops, pushed a change up for it to use the content url instead

**Comment by linb1** [comment]
updated url correctly this time 😅
image

**Review by jordanwade — APPROVED** [review]
Looks Good!

**Pull request merged**
