### PR TITLE
Fixed issue in Search bar placeholder overlap with icon

### PR DESCRIPTION
**Pull request by rajitharussel**
## 🐛 Issue

when using an small screen size, Search bar place holder text overlaps with user avatar

## ✏️ Solution

un necessary padding removed which causes this text overlap

## 🔬 To Test

1. Open feed contains search and check the Search bar in mobile screens.
2. http://localhost:3000/?id=facing-your-saul-TWVkaWFDb250ZW50SXRlbS0wNzgwMWQ0Ni1iYWE4LTQ0ZGUtODEwNi1jMThlODA5YmNlZWI%3D

#### Before
Screenshot 2024-02-19 at 16 11 49

#### After

Simulator Screenshot - iPhone 15 Pro Max - 2024-02-15 at 07 19 06

### CODE REVIEW

**Comment by redreceipt** [comment]
@rajitharussel can you show what tit looks like when there's more text than will fit in the box

**Comment by rajitharussel** [comment]
> @rajitharussel can you show what it looks like when there's more text than will fit in the box

https://github.com/ApollosProject/apollos-embeds/assets/138706838/e9da9316-286c-4a3c-8d45-954d8ec8f6b4

**Comment by redreceipt** [comment]
Can we change the placeholder copy to "What are you looking for?". The current is too long

Screenshot 2024-02-12 at 10 33 21 AM

**Comment by rajitharussel** [comment]
> Can we change the placeholder copy to "What are you looking for?". The current is too long
> 
> Screenshot 2024-02-12 at 10 33 21 AM

@redreceipt only for the mobile or always?

**Comment by redreceipt** [comment]
I think always. @nlewis84 overrule me though

**Comment by nlewis84** [comment]
@rajitharussel Sorry I didn't see this earlier. We can do "What are you looking for?" always.

**Comment by nlewis84** [comment]
Can you attach some before and after photos to this? It would be super helpful if you dropped a link to a feed into the test instructions. Will need a rebase, also.

**Comment by rajitharussel** [comment]
> @rajitharussel Sorry I didn't see this earlier. We can do "What are you looking for?" always.



> > Can we change the placeholder copy to "What are you looking for?". The current is too long
> > Screenshot 2024-02-12 at 10 33 21 AM
> 
> @redreceipt only for the mobile or always?

added

**Review by nlewis84 — APPROVED** [review]
👍

**Comment by rajitharussel** [comment]
> Can you attach some before and after photos to this? It would be super helpful if you dropped a link to a feed into the test instructions. Will need a rebase, also.

updated the description

**Pull request merged**
