### PR TITLE
Fix auth details merge

### PR DESCRIPTION
**Pull request by jordanwade**
## ✏️ Description

This PR adds the merge profile functionality to web-embeds. This fixes issues with duplicated users and it requires users to have a first and last name.

copilot:summary

## 🔬 To Test

1. Running Cluster Locally in your preferred database management tool run the following to delete and insert profiles for `appstoretester@apollos.app` account 
```
delete from table_history;
delete from comment_notification
DELETE from people where email = 'appstoretester@apollos.app' and church_slug = 'apollos_demo';
```
```
INSERT INTO "public"."people"("first_name","last_name","email","birth_date","profile_image_url","gender","campus_id","apollos_user","apollos_type","origin_id","origin_type","created_at","updated_at","church_slug","phone")
VALUES
(NULL,NULL,E'appstoretester@apollos.app',NULL,NULL,E'UNKNOWN',NULL,FALSE,E'Person',E'159',E'rock',E'2023-02-01 17:08:34.463054+00',E'2023-02-01 17:08:34.463054+00',E'apollos_demo',NULL),
(E'Apple',E'Tester',E'appstoretester@apollos.app',E'2022-08-27 00:00:00+00',NULL,E'MALE',E'9d7203fe-72f6-418f-a269-f670a779deb5',FALSE,E'Person',E'132',E'rock',E'2023-02-01 17:08:34.463054+00',E'2023-02-01 17:08:34.463054+00',E'apollos_demo',NULL),
(E'Apollos',E'Fake 2',E'appstoretester@apollos.app',E'2020-11-18 00:00:00+00',NULL,E'MALE',E'47c4a1d2-0c49-4dcb-9151-3eef00d42fcc',FALSE,E'Person',E'158',E'rock',E'2023-02-01 17:08:34.463054+00',E'2023-02-01 17:08:34.463054+00',E'apollos_demo',NULL),
(E'Apollos',E'Fake 1',E'appstoretester@apollos.app',NULL,NULL,E'MALE',E'47c4a1d2-0c49-4dcb-9151-3eef00d42fcc',FALSE,E'Person',E'157',E'rock',E'2023-02-01 17:08:34.463054+00',E'2023-02-01 17:08:34.463054+00',E'apollos_demo',NULL);
```
2. Login in as `appstoretester@apollos.app` pin code is `1234`. You will need to change the `codeLength` to 4 in the front-end inside the AuthConfirm.js
3. You should see screen to select a profile. Click one.
4. You should be logged in and you can check your DB to make sure the user you clicked on has TRUE set for the `APOLLOS_USER`

## 📸 Screenshots

Walkthrough video of it working and how to test.
https://www.loom.com/share/222a9165eb084c8a9c67851f9ce65185?sid=5bf0358b-e5d7-4106-9896-a88302b343fc

## 🧐 Detailed Changes

copilot:walkthrough

## 📝 Checklist

- [ ] I have performed a self-review of my code
- [ ] I have tested my code works in the project (nothing breaks)
- [ ] I have commented my code in hard-to-understand areas
- [ ] New and existing tests and linting pass locally with my changes
- [ ] I have made corresponding changes to the documentation (new envs?)
- [ ] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

### CODE REVIEW

**Comment by calebpanza** [comment]
@jordanwade looks like there are some merge conflicts. I'll hold off review until those are resolved to make sure I'm testing the right stuff.

**Comment by jordanwade** [comment]
@calebpanza should be good to go when you have time next week. Thanks!

**Comment by jordanwade** [comment]
@linb1 when you get a chance can you give this a run through?

**Comment by linb1** [comment]
@jordanwade I wasn't able to get to the profile selection screen yesterday, but it might be something I messed up on my end. Going to try again

**Review by linb1 — APPROVED** [review]

**Pull request merged**
