### PR TITLE
fix: import React in every file that uses it

### PR DESCRIPTION
**Pull request by nlewis84**
## 🐛 Issue

Closes [All Video Content web embeds are crashing](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/7240785663)

## ✏️ Solution

- Add React in every file that uses it (per the `README`)

## 🔬 To Test

1. It works locally with or without this, so deploy? 🤷

### CODE REVIEW

**Comment by nlewis84** [comment]
* **#201** <a href="https://app.graphite.dev/github/pr/ApollosProject/apollos-embeds/201?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nlewis84 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by nlewis84** [comment]
@redreceipt Have you seen web embeds bomb out before because of this missing import?

**Comment by redreceipt** [comment]
@nlewis84 this still valid?

**Comment by nlewis84** [comment]
According the readme it is, but I think it's okay to close since it hasn't caused trouble yet.

**Pull request closed without merging**
