### PR TITLE
fix: when clicking events from a link the breadcrumbs are broken

### PR DESCRIPTION
**Pull request by Sherange**
## 🐛 Issue

When clicking events from a link the breadcrumbs are broken https://github.com/ApollosProject/apollos-embeds/issues/181

## ✏️ Solution

breadcrumb issues - remove last item from  breadcrumb on ContentSingle
title issue - add missing title param

## 🔬 To Test

1. Navigate to series item 
2. Keep selecting single content items of that series

## 📸 Screenshots

https://github.com/ApollosProject/apollos-embeds/assets/28708210/b9dca95c-6421-47b7-80fc-86b2f20f9cc3

### CODE REVIEW

**Comment by redreceipt** [comment]
@Sherange does this fix the events issue? can you show a screenshot of an event with "Events > TITLE" breadcrumbs

**Comment by Sherange** [comment]
> @Sherange does this fix the events issue? can you show a screenshot of an event with "Events > TITLE" breadcrumbs

@redreceipt fyr

https://github.com/ApollosProject/apollos-embeds/assets/28708210/81646281-2e36-4460-8135-5ef2870930cf

**Comment by redreceipt** [comment]
@Sherange what about starting from this page? https://liquid-church.webflow.io/events

**Comment by Sherange** [comment]
> @Sherange what about starting from this page? https://liquid-church.webflow.io/events

Yes issue was we are not passing correct title param to create breadcrumbs on event contents

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
