### PR TITLE
Micro service

### PR DESCRIPTION
**Pull request by jordanwade**
This PR restructures the Web Embeds project to account for a micro-service/Vercel site that deploys out of the `micro-service` folder. I've also pulled out all the components to run the embeds project into the packages/web-shared so both embeds and the micro-service can be deployed independently.

After Merge:
I need to go into Vercel and update the deploy branch to be `main` instead of this branch 

To Test micro-service:
Local:
http://willow-creek.localhost:3000/?root=FeatureFeed-affd0ea5-cdcc-429b-9630-c8535664a884

Live:
http://willow-creek.apollos.church/?root=FeatureFeed-affd0ea5-cdcc-429b-9630-c8535664a884

https://cedar-creek.apollos.church/?root=FeatureFeed-5aae43e6-3526-4cd2-8dfe-771d2ce8a333

Note: Please test the `web-embeds` app as well to make sure it is still working the same as before.

### CODE REVIEW

**Review by linb1 — CHANGES_REQUESTED** [review]
I'm running into this error when clicking the test link and trying to run web embed, though I think its just an import issue due to the file structure changing

**Comment by jordanwade** [comment]
@linb1 is that local or one of the live links?

**Comment by jordanwade** [comment]
If local try running yarn

**Comment by jordanwade** [comment]
@linb1 I also forgot to mention I'm switching over to using yarn instead of npm for this project to match the other apollos projects.

**Comment by linb1** [comment]
@jordanwade I've run yarn, now I'm getting a white screen with a seperate error
image

**Comment by linb1** [comment]
@jordanwade I think the InteractWhenLoaded folder didnt get merged in, but i can add it back 
image

**Comment by linb1** [comment]
@jordanwade Pushed the commit, it's all working for me now

**Review by linb1 — APPROVED** [review]

**Pull request merged**
