### PR TITLE
🛠 Breadcrumbs not working correctly when navigating backwards in the browser 

### PR DESCRIPTION
**Pull request by linb1**
## Basecamp Scope

[Breadcrumbs not working correctly with browser back button and using keyboard `cmd left arrow`](https://3.basecamp.com/3926363/buckets/27088350/todos/6018447603)

## What was done?

1. Added useEffect to breadcrumb component
2. Listens for `popstate` event. Removes last item of state
3. Breadcrumb should now disappear when it's suppose to (at the root)

_Note: The breadcrumb also resets when the user goes forward as well, looking into fix for that_

Before:

https://user-images.githubusercontent.com/68402088/231886734-69cd3ab0-7f14-4ed3-baa3-d0b5c1f56a21.mov

After:

https://user-images.githubusercontent.com/68402088/231886753-693e7041-b046-44c2-b2fa-c4e3b02ae739.mov

### CODE REVIEW

**Review by jordanwade — CHANGES_REQUESTED** [review]
@linb1 I think your breadcrumb reset is a little too aggressive. When I navigate to a series and then a child item in that series I would expect the breadcrumb to show my full navigation path from `feature > transform > marks of a transformed life` then when I go back I should see `feature > transform` on the transform series item. Does that make sense?


https://user-images.githubusercontent.com/2528817/232151956-903750f4-b7f5-4793-adb6-7c6a20dc77e9.mp4

**Comment by linb1** [comment]
@jordanwade That makes sense. My understanding of how it work was off so my implementation here definitely isn't sufficient. I'll keep working on this one

**Comment by jordanwade** [comment]
@linb1 if this gets to complicated @conrad-vanl mentioned we can table the Breadcrumb feature for now.

So, let's time box this and if you don't get a solution going soon we can put a pin in it and instead just disable the breadcrumbs component.

**Comment by linb1** [comment]
@jordanwade I've updated the logic to the component. This functionality is still kind of wonky. Certain combinations of refreshes and forward movement can break the breadcrumb. If you test it and still find it not ready, then we can put a pin on it and disable it

https://user-images.githubusercontent.com/68402088/232839953-aa9d9611-4295-4493-9dc2-320bd5a37ca1.mov

**Comment by jordanwade** [comment]
@linb1 yeah, there is still some weird stuff going on. Can you just remove the importing and rendering of the Breadcrumbs component in the `FeatureFeed.js` component. We can leave the actual Breadcrumbs component in the codebase for now just in-case we want to revisit this feature soon. 

Then we can merge this PR

CleanShot 2023-04-24 at 10 56 27@2x

**Comment by linb1** [comment]
@jordanwade Removed 👍. I can go ahead and merge

**Pull request merged**
