### PR TITLE
(Web) Reduce the display size of images on the Content Single

### PR DESCRIPTION
**Pull request by linb1**
## Basecamp Scope

[(Web) Reduce the display size of images on the Content Single](https://3.basecamp.com/3926363/buckets/27088350/todos/6459537200)

## What was done?

1. reduce image width on larger screens + added background color to (according to chatGPT): "mitigate the visual impact of stretching the image while maintaining a cohesive design"
2. Added max width of 750px to images (might not be necessary when higher res pictures are uploaded)

_Note: This probably can be run by a designer as well_

## How to test?

1. Go to any content with image, should have responsiveness as shown below

https://github.com/ApollosProject/apollos-embeds/assets/68402088/0e249309-84c7-4510-bd5b-65d51ed9874c

Before (takes up entire width):
image

### CODE REVIEW

**Comment by jordanwade** [comment]
@linb1 what do you think about limiting the entire content width to 750px? That way we don't need that gray back behind the images

**Comment by linb1** [comment]
@jordanwade That works too. At first I was thinking on larger screens the gap between the image and the edge might be too much, but now I think it's not too bad. I can push up the change for that

image

**Comment by jordanwade** [comment]
Sorry, I meant limit the entire screen content to be max 750. 
image

**Comment by linb1** [comment]
@jordanwade My bad, should be done!

**Review by jordanwade — APPROVED** [review]
🙌

**Pull request merged**
