### PR TITLE
chore: Update PR Template

### PR DESCRIPTION
**Pull request by vinnyjth**
## ✏️ Description

Updates the PR template to match the flow described [here](https://3.basecamp.com/3926363/buckets/27088350/messages/6705670071)

## 🔬 To Test

1. hmmmm 🤔 
2. Maybe make a pr once this is merged? 

### Screenshots

CleanShot 2023-10-31 at 09 18 47@2x

### CODE REVIEW

**Comment by jordanwade** [comment]
@vinnyjth @calebpanza do you guys think it is ok to do away with the check list? One major pain point I always run into is when .envs change or get added. Are we ok with shipping code that causes this type of issue when reviewing and running apps or should we stop ignoring the existing PR template and require checking off those items? The other sections I'm cool with changing. 

I just want to figure out how to reduce some of those easy gotchas before requesting a review. If that is done in a different way that is cool too. I'm not sure if the checklist is the right solve, but just doing away with it seems to be a miss.

Also, I understand not every PR needs that section that is why I added `<!-- You can erase any parts of this template not applicable to your Pull Request. -->`. 

I also can easily be convinced to change my opinion if the goal is to just create consistence and simplify the PR templates across all apps. 😄

**Comment by vinnyjth** [comment]
@jordanwade I do see a lot of value conceptually with keeping the checklist, but I found it fell short in practice. 

When I audited PRs on platforms (which has a checklist) it seemed that in almost all cases one of the three things happened 

- the checklist was ignored (all empty) 
- the checklist was checked off (with no clear or helpful indication that it was actually followed) 
- the checklist was correctly partially checked off, but never followed up on by a reviewer. 

I do think it's important to make sure `.env` changes are documented and handled during a PR review, but I think we should find ways to do that more automatically. `platforms` is a good example - we now run a `bitrise` build when a PR is opened, and when a new config value is utilized but not added the `bitrise` build fails.

**Comment by jordanwade** [comment]
> I do think it's important to make sure `.env` changes are documented and handled during a PR review, but I think we should find ways to do that more automatically. `platforms` is a good example - we now run a `bitrise` build when a PR is opened, and when a new config value is utilized but not added the `bitrise` build fails.

@vinnyjth Cool, do you have that on your list to figure out something automatic for the other platforms web, admin? Do we need an Engineering Roadmap or should we put stuff like that on the main Apollos Roadmap?

**Review by jordanwade — APPROVED** [review]

**Comment by vinnyjth** [comment]
> Cool, do you have that on your list to figure out something automatic for the other platforms web, admin? Do we need an Engineering Roadmap or should we put stuff like that on the main Apollos Roadmap?

It's a mix, some of these CI/CD related topics I've captured (particularly on `platforms`) on the Apollos Roadmap.  Often times execution on these types of problems also happens as a retro outcome. 

I would LOVE to jam on your ideas for how to automate more of the PR "sanity check" process as well :D

**Pull request merged**
